<script src="resource/Resources/libraries/jQuery/01_09_01/jquery4b95.js?cdv=118" type="text/javascript"></script>
<script src="resource/Resources/libraries/jQuery-UI/01_11_03/jquery-ui4b95.js?cdv=118" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.dd.min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.magnific-popup.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/modernizr.custom.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/HorizontalMenu.min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.flexslider-min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.easytabs.min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.mmenu.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.carouFredSel.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.mousewheel.min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.touchSwipe.min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.transit.min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/jquery.ba-throttle-debounce.min.js" type="text/javascript"></script>
<script src="resource/portals/_default/skins/dhbk/js/common.js" type="text/javascript"></script>